In [26]:
import pandas as pd

In [27]:
file = "300352-180-meteorologicos-horarios-csv.csv"
df = pd.read_csv(file, sep=";")

In [28]:
df

,PROVINCIA,MUNICIPIO,ESTACION,MAGNITUD,PUNTO_MUESTREO,ANO,MES,DIA,H01,V01,...,H20,V20,H21,V21,H22,V22,H23,V23,H24,V24
0,28,79,102,81,NaN,2025,1,1,0.7,V,...,0.0,V,0.1,V,0.5,V,0.6,V,0.8,V
1,28,79,102,81,NaN,2025,1,2,0.8,V,...,0.9,V,0.5,V,0.8,V,0.7,V,0.2,V
2,28,79,102,81,NaN,2025,1,3,0.6,V,...,0.2,V,0.3,V,0.4,V,0.4,V,0.8,V
3,28,79,102,81,NaN,2025,1,4,0.3,V,...,1.6,V,1.1,V,0.8,V,1.1,V,0.8,V
4,28,79,102,81,NaN,2025,1,5,0.8,V,...,3.2,V,2.8,V,2.4,V,2.2,V,3.0,V
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39379,28,79,8,86,NaN,2026,2,24,51.0,V,...,35.0,V,37.0,V,39.0,V,44.0,V,46.0,V
39380,28,79,8,86,NaN,2026,2,25,45.0,V,...,33.0,V,37.0,V,39.0,V,42.0,V,43.0,V
39381,28,79,8,86,NaN,2026,2,26,43.0,V,...,28.0,V,31.0,V,34.0,V,35.0,V,39.0,V
39382,28,79,8,86,NaN,2026,2,27,42.0,V,...,41.0,V,43.0,V,45.0,V,48.0,V,50.0,V
39383,28,79,8,86,NaN,2026,2,28,48.0,V,...,44.0,V,48.0,V,52.0,V,57.0,V,67.0,V

In [29]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
PROVINCIA,39384.0,28.000000,0.000000,28.0,28.0,28.00,28.0,28.0
MUNICIPIO,39384.0,79.000000,0.000000,79.0,79.0,79.00,79.0,79.0
ESTACION,39384.0,76.538087,34.969533,4.0,54.0,102.00,107.0,115.0
MAGNITUD,39384.0,84.821273,2.605307,81.0,83.0,86.00,87.0,89.0
PUNTO_MUESTREO,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ANO,39384.0,2025.140336,0.347340,2025.0,2025.0,2025.00,2025.0,2026.0
MES,39384.0,5.822441,3.655753,1.0,2.0,6.00,9.0,12.0
DIA,39384.0,15.656104,8.762671,1.0,8.0,16.00,23.0,31.0
H01,39384.0,116.579702,259.745070,-6.3,1.0,18.40,74.0,960.0
H02,39384.0,116.205525,259.283746,-7.2,0.9,17.60,76.0,959.0
H03,39384.0,115.956759,259.082902,-8.0,0.9,16.80,77.0,959.0
H04,39384.0,116.281274,259.199217,-8.7,0.8,16.40,79.0,959.0
H05,39384.0,116.328362,259.226353,-9.5,0.7,15.70,80.0,959.0
H06,39384.0,116.396085,259.200443,-9.9,0.7,15.10,80.0,959.0
H07,39384.0,115.557704,258.104327,-10.2,0.7,14.25,81.0,960.0
H08,39384.0,117.258727,258.348387,-10.6,1.0,17.10,82.0,960.0
H09,39384.0,122.051582,257.709332,-10.6,2.2,22.20,86.0,961.0
H10,39384.0,131.386484,260.401949,-8.5,3.2,27.80,89.0,961.0
H11,39384.0,141.737569,268.816126,-3.6,4.3,30.00,89.0,961.0
H12,39384.0,152.646105,281.246552,-1.5,5.6,31.00,91.0,961.0
H13,39384.0,160.603514,292.135564,-0.4,6.9,30.60,93.0,1012.0
H14,39384.0,164.201422,297.801348,-0.8,7.7,30.00,96.0,1078.0
H15,39384.0,163.233437,297.039744,-0.4,8.1,29.00,97.0,1096.0
H16,39384.0,157.993170,289.862687,0.0,8.4,28.30,96.0,1024.0
H17,39384.0,148.966786,278.667363,0.0,8.1,28.00,92.0,958.0
H18,39384.0,138.751864,268.769988,0.0,7.4,26.50,83.0,958.0
H19,39384.0,130.829090,262.674991,-0.6,3.4,24.60,79.0,959.0
H20,39384.0,123.967665,258.847273,-1.4,2.1,23.00,78.0,959.0
H21,39384.0,118.661200,258.105630,-3.5,1.6,22.10,74.0,959.0
H22,39384.0,116.023601,258.112678,-4.5,1.0,19.80,70.0,960.0
H23,39384.0,114.407729,256.788493,-4.9,0.8,18.75,71.0,960.0
H24,39384.0,106.938048,249.051823,-5.6,0.2,14.65,68.0,960.0

In [30]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 39384 entries, 0 to 39383
Data columns (total 56 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PROVINCIA       39384 non-null  int64
 1   MUNICIPIO       39384 non-null  int64
 2   ESTACION        39384 non-null  int64
 3   MAGNITUD        39384 non-null  int64
 4   PUNTO_MUESTREO  0 non-null      float64
 5   ANO             39384 non-null  int64
 6   MES             39384 non-null  int64
 7   DIA             39384 non-null  int64
 8   H01             39384 non-null  float64
 9   V01             39384 non-null  str
 10  H02             39384 non-null  float64
 11  V02             39384 non-null  str
 12  H03             39384 non-null  float64
 13  V03             39384 non-null  str
 14  H04             39384 non-null  float64
 15  V04             39384 non-null  str
 16  H05             39384 non-null  float64
 17  V05             39384 non-null  str
 18  H06             39384 non-null  float64
 19  V06             39384 non-null  str
 20  H07             39384 non-null  float64
 21  V07             39384 non-null  str
 22  H08             39384 non-null  float64
 23  V08             39384 non-null  str
 24  H09             39384 non-null  float64
 25  V09             39384 non-null  str
 26  H10             39384 non-null  float64
 27  V10             39384 non-null  str
 28  H11             39384 non-null  float64
 29  V11             39384 non-null  str
 30  H12             39384 non-null  float64
 31  V12             39384 non-null  str
 32  H13             39384 non-null  float64
 33  V13             39384 non-null  str
 34  H14             39384 non-null  float64
 35  V14             39384 non-null  str
 36  H15             39384 non-null  float64
 37  V15             39384 non-null  str
 38  H16             39384 non-null  float64
 39  V16             39384 non-null  str
 40  H17             39384 non-null  float64
 41  V17             39384 non-null  str
 42  H18             39384 non-null  float64
 43  V18             39384 non-null  str
 44  H19             39384 non-null  float64
 45  V19             39384 non-null  str
 46  H20             39384 non-null  float64
 47  V20             39384 non-null  str
 48  H21             39384 non-null  float64
 49  V21             39384 non-null  str
 50  H22             39384 non-null  float64
 51  V22             39384 non-null  str
 52  H23             39384 non-null  float64
 53  V23             39384 non-null  str
 54  H24             39384 non-null  float64
 55  V24             39384 non-null  str
dtypes: float64(25), int64(7), str(24)
memory usage: 16.8 MB

In [31]:
codigos_estaciones = {
    "102": "J.M.D. Moratalaz",
    "103": "J.M.D. Villaverde",
    "104": "E.D.A.R. La China",
    "106": "Centro Mpal. De Acústica",
    "107": "J.M.D. Hortaleza",
    "108": "Peñagrande",
    "109": "J.M.D. Chamberí",
    "110": "J.M.D. Centro",
    "111": "J.M.D. Chamartín",
    "112": "J.M.D. Vallecas 1",
    "113": "J.M.D. Vallecas 2",
    "114": "Matadero 01",
    "115": "Matadero 02",
    "004": "Plaza España",
    "008": "Escuelas Aguirre",
    "016": "Arturo Soria",
    "018": "Farolillo",
    "024": "Casa de Campo",
    "035": "Plaza del Carmen",
    "036": "Moratalaz",
    "038": "Cuatro Caminos",
    "039": "Barrio del Pilar",
    "054": "Ensanche de Vallecas",
    "056": "Plaza Elíptica",
    "058": "El Pardo",
    "059": "Juan Carlos I"
}

In [32]:
codigos_magnitudes = {
    80: {"parametro": "Radiación ultravioleta", "unidad": "mW/m2"},
    81: {"parametro": "Velocidad del viento", "unidad": "m/s"},
    82: {"parametro": "Dirección del viento", "unidad": "grados"},
    83: {"parametro": "Temperatura", "unidad": "ºC"},
    86: {"parametro": "Humedad relativa", "unidad": "%"},
    87: {"parametro": "Presión barométrica", "unidad": "mb"},
    88: {"parametro": "Radiación solar", "unidad": "W/m2"},
    89: {"parametro": "Precipitación", "unidad": "l/m2"}
}

In [33]:
df["ESTACION_NOMBRE"] = df["ESTACION"].astype(str).map(codigos_estaciones)
df["MAGNITUD_NOMBRE"] = df["MAGNITUD"].map(lambda x: codigos_magnitudes[x]["parametro"])
df["UNIDAD"] = df["MAGNITUD"].map(lambda x: codigos_magnitudes[x]["unidad"])

In [34]:
df.head()

,PROVINCIA,MUNICIPIO,ESTACION,MAGNITUD,PUNTO_MUESTREO,ANO,MES,DIA,H01,V01,...,V21,H22,V22,H23,V23,H24,V24,ESTACION_NOMBRE,MAGNITUD_NOMBRE,UNIDAD
0,28,79,102,81,NaN,2025,1,1,0.7,V,...,V,0.5,V,0.6,V,0.8,V,J.M.D. Moratalaz,Velocidad del viento,m/s
1,28,79,102,81,NaN,2025,1,2,0.8,V,...,V,0.8,V,0.7,V,0.2,V,J.M.D. Moratalaz,Velocidad del viento,m/s
2,28,79,102,81,NaN,2025,1,3,0.6,V,...,V,0.4,V,0.4,V,0.8,V,J.M.D. Moratalaz,Velocidad del viento,m/s
3,28,79,102,81,NaN,2025,1,4,0.3,V,...,V,0.8,V,1.1,V,0.8,V,J.M.D. Moratalaz,Velocidad del viento,m/s
4,28,79,102,81,NaN,2025,1,5,0.8,V,...,V,2.4,V,2.2,V,3.0,V,J.M.D. Moratalaz,Velocidad del viento,m/s

In [35]:
rows = []

for _, row in df.iterrows():
    for h in range(1, 25):
        valor = row[f"H{h:02d}"]
        valid = row[f"V{h:02d}"]
        
        fecha = pd.Timestamp(row["ANO"], row["MES"], row["DIA"]) + pd.Timedelta(hours=h-1)

        rows.append({
            "PROVINCIA": row["PROVINCIA"],
            "MUNICIPIO": row["MUNICIPIO"],
            "ESTACION": row["ESTACION"],
            "ESTACION_NOMBRE": row["ESTACION_NOMBRE"],
            "MAGNITUD": row["MAGNITUD"],
            "MAGNITUD_NOMBRE": row["MAGNITUD_NOMBRE"],
            "UNIDAD": row["UNIDAD"],
            "ANO": row["ANO"],
            "MES": row["MES"],
            "DIA": row["DIA"],
            "HORA": h,
            "VALOR": valor,
            "VALIDACION": valid,
            "FECHA_HORA": fecha

        })

df_long = pd.DataFrame(rows)

In [36]:
df_long

,PROVINCIA,MUNICIPIO,ESTACION,ESTACION_NOMBRE,MAGNITUD,MAGNITUD_NOMBRE,UNIDAD,ANO,MES,DIA,HORA,VALOR,VALIDACION,FECHA_HORA
0,28,79,102,J.M.D. Moratalaz,81,Velocidad del viento,m/s,2025,1,1,1,0.7,V,2025-01-01 00:00:00
1,28,79,102,J.M.D. Moratalaz,81,Velocidad del viento,m/s,2025,1,1,2,1.1,V,2025-01-01 01:00:00
2,28,79,102,J.M.D. Moratalaz,81,Velocidad del viento,m/s,2025,1,1,3,1.3,V,2025-01-01 02:00:00
3,28,79,102,J.M.D. Moratalaz,81,Velocidad del viento,m/s,2025,1,1,4,0.0,N,2025-01-01 03:00:00
4,28,79,102,J.M.D. Moratalaz,81,Velocidad del viento,m/s,2025,1,1,5,0.9,V,2025-01-01 04:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945211,28,79,8,NaN,86,Humedad relativa,%,2026,2,28,20,44.0,V,2026-02-28 19:00:00
945212,28,79,8,NaN,86,Humedad relativa,%,2026,2,28,21,48.0,V,2026-02-28 20:00:00
945213,28,79,8,NaN,86,Humedad relativa,%,2026,2,28,22,52.0,V,2026-02-28 21:00:00
945214,28,79,8,NaN,86,Humedad relativa,%,2026,2,28,23,57.0,V,2026-02-28 22:00:00
945215,28,79,8,NaN,86,Humedad relativa,%,2026,2,28,24,67.0,V,2026-02-28 23:00:00

In [37]:
df_valores = df_long.pivot_table(
    index=["PROVINCIA", "MUNICIPIO", "ESTACION", "ESTACION_NOMBRE", "FECHA_HORA"],
    columns="MAGNITUD_NOMBRE",
    values="VALOR",
    aggfunc="first"
)

In [38]:
df_valid = df_long.pivot_table(
    index=["PROVINCIA", "MUNICIPIO", "ESTACION", "ESTACION_NOMBRE", "FECHA_HORA"],
    columns="MAGNITUD_NOMBRE",
    values="VALIDACION",
    aggfunc="first"
)

In [39]:
df_valid = df_valid.add_suffix("_valid")

In [40]:
df_wide = pd.concat([df_valores, df_valid], axis=1).reset_index()

In [41]:
df = df_wide.sort_values(by="FECHA_HORA", ascending=False)
df

MAGNITUD_NOMBRE,PROVINCIA,MUNICIPIO,ESTACION,ESTACION_NOMBRE,FECHA_HORA,Dirección del viento,Humedad relativa,Precipitación,Presión barométrica,Radiación solar,Temperatura,Velocidad del viento,Dirección del viento_valid,Humedad relativa_valid,Precipitación_valid,Presión barométrica_valid,Radiación solar_valid,Temperatura_valid,Velocidad del viento_valid
127991,28,79,115,Matadero 02,2026-02-28 23:00:00,NaN,65.0,NaN,NaN,NaN,11.7,NaN,NaN,V,NaN,NaN,NaN,V,NaN
118127,28,79,114,Matadero 01,2026-02-28 23:00:00,NaN,66.0,NaN,NaN,NaN,12.1,NaN,NaN,V,NaN,NaN,NaN,V,NaN
30359,28,79,104,E.D.A.R. La China,2026-02-28 23:00:00,151.0,NaN,NaN,NaN,NaN,NaN,0.9,V,NaN,NaN,NaN,NaN,NaN,V
20255,28,79,103,J.M.D. Villaverde,2026-02-28 23:00:00,122.0,68.0,0.0,953.0,0.0,8.3,0.8,V,V,V,V,V,V,V
40511,28,79,106,Centro Mpal. De Acústica,2026-02-28 23:00:00,160.0,64.0,0.0,954.0,0.0,10.1,1.1,V,V,V,V,V,V,V
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118128,28,79,115,Matadero 02,2025-01-01 00:00:00,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,N,NaN,NaN,NaN,N,NaN
20256,28,79,104,E.D.A.R. La China,2025-01-01 00:00:00,46.0,NaN,NaN,NaN,NaN,NaN,0.0,V,NaN,NaN,NaN,NaN,NaN,V
40512,28,79,107,J.M.D. Hortaleza,2025-01-01 00:00:00,32.0,75.0,0.0,948.0,1.0,1.5,0.8,V,V,V,V,V,V,V
50688,28,79,108,Peñagrande,2025-01-01 00:00:00,196.0,77.0,0.0,951.0,1.0,0.1,0.6,V,V,V,V,V,V,V
0,28,79,102,J.M.D. Moratalaz,2025-01-01 00:00:00,55.0,72.0,0.0,949.0,1.0,1.4,0.7,V,V,V,V,V,V,V

In [42]:
df.to_csv("historico_expandido.csv", index=False, sep=";")

In [43]:
ultima_hora = df["FECHA_HORA"].max()
ultima_hora

Timestamp('2026-02-28 23:00:00')

In [44]:
df_ultima_hora = df[df["FECHA_HORA"] == ultima_hora]
df_ultima_hora.to_csv("ultima_hora_23.csv", index=False)
df_ultima_hora

MAGNITUD_NOMBRE,PROVINCIA,MUNICIPIO,ESTACION,ESTACION_NOMBRE,FECHA_HORA,Dirección del viento,Humedad relativa,Precipitación,Presión barométrica,Radiación solar,Temperatura,Velocidad del viento,Dirección del viento_valid,Humedad relativa_valid,Precipitación_valid,Presión barométrica_valid,Radiación solar_valid,Temperatura_valid,Velocidad del viento_valid
127991,28,79,115,Matadero 02,2026-02-28 23:00:00,NaN,65.0,NaN,NaN,NaN,11.7,NaN,NaN,V,NaN,NaN,NaN,V,NaN
118127,28,79,114,Matadero 01,2026-02-28 23:00:00,NaN,66.0,NaN,NaN,NaN,12.1,NaN,NaN,V,NaN,NaN,NaN,V,NaN
30359,28,79,104,E.D.A.R. La China,2026-02-28 23:00:00,151.0,NaN,NaN,NaN,NaN,NaN,0.9,V,NaN,NaN,NaN,NaN,NaN,V
20255,28,79,103,J.M.D. Villaverde,2026-02-28 23:00:00,122.0,68.0,0.0,953.0,0.0,8.3,0.8,V,V,V,V,V,V,V
40511,28,79,106,Centro Mpal. De Acústica,2026-02-28 23:00:00,160.0,64.0,0.0,954.0,0.0,10.1,1.1,V,V,V,V,V,V,V
98855,28,79,112,J.M.D. Vallecas 1,2026-02-28 23:00:00,NaN,65.0,NaN,NaN,NaN,11.7,NaN,NaN,V,NaN,NaN,NaN,V,NaN
60863,28,79,108,Peñagrande,2026-02-28 23:00:00,101.0,61.0,0.0,947.0,0.0,9.5,1.1,V,V,V,V,V,V,V
69815,28,79,109,J.M.D. Chamberí,2026-02-28 23:00:00,NaN,63.0,NaN,NaN,NaN,12.2,NaN,NaN,V,NaN,NaN,NaN,V,NaN
79631,28,79,110,J.M.D. Centro,2026-02-28 23:00:00,NaN,63.0,NaN,NaN,NaN,12.0,NaN,NaN,V,NaN,NaN,NaN,V,NaN
50687,28,79,107,J.M.D. Hortaleza,2026-02-28 23:00:00,85.0,67.0,0.0,944.0,0.0,9.2,0.9,V,V,V,V,V,V,V
89231,28,79,111,J.M.D. Chamartín,2026-02-28 23:00:00,NaN,62.0,NaN,NaN,NaN,11.6,NaN,NaN,V,NaN,NaN,NaN,V,NaN
10175,28,79,102,J.M.D. Moratalaz,2026-02-28 23:00:00,115.0,69.0,0.0,944.0,0.0,7.3,2.1,V,V,V,V,V,V,V
108551,28,79,113,J.M.D. Vallecas 2,2026-02-28 23:00:00,NaN,62.0,NaN,NaN,NaN,12.7,NaN,NaN,V,NaN,NaN,NaN,V,NaN

In [45]:
df_sin_ultima_hora = df[df["FECHA_HORA"] != ultima_hora]

In [46]:
ultima_hora = df_sin_ultima_hora["FECHA_HORA"].max()
ultima_hora

Timestamp('2026-02-28 22:00:00')

In [47]:
df_ultima_hora = df_sin_ultima_hora[df_sin_ultima_hora["FECHA_HORA"] == ultima_hora]
df_ultima_hora.to_json("ultima_hora_22.json", orient="records", date_format="iso")
df_ultima_hora

MAGNITUD_NOMBRE,PROVINCIA,MUNICIPIO,ESTACION,ESTACION_NOMBRE,FECHA_HORA,Dirección del viento,Humedad relativa,Precipitación,Presión barométrica,Radiación solar,Temperatura,Velocidad del viento,Dirección del viento_valid,Humedad relativa_valid,Precipitación_valid,Presión barométrica_valid,Radiación solar_valid,Temperatura_valid,Velocidad del viento_valid
118126,28,79,114,Matadero 01,2026-02-28 22:00:00,NaN,56.0,NaN,NaN,NaN,13.5,NaN,NaN,V,NaN,NaN,NaN,V,NaN
69814,28,79,109,J.M.D. Chamberí,2026-02-28 22:00:00,NaN,51.0,NaN,NaN,NaN,13.6,NaN,NaN,V,NaN,NaN,NaN,V,NaN
50686,28,79,107,J.M.D. Hortaleza,2026-02-28 22:00:00,52.0,58.0,0.0,944.0,0.0,9.9,1.1,V,V,V,V,V,V,V
108550,28,79,113,J.M.D. Vallecas 2,2026-02-28 22:00:00,NaN,54.0,NaN,NaN,NaN,13.5,NaN,NaN,V,NaN,NaN,NaN,V,NaN
79630,28,79,110,J.M.D. Centro,2026-02-28 22:00:00,NaN,53.0,NaN,NaN,NaN,13.1,NaN,NaN,V,NaN,NaN,NaN,V,NaN
98854,28,79,112,J.M.D. Vallecas 1,2026-02-28 22:00:00,NaN,57.0,NaN,NaN,NaN,12.6,NaN,NaN,V,NaN,NaN,NaN,V,NaN
89230,28,79,111,J.M.D. Chamartín,2026-02-28 22:00:00,NaN,52.0,NaN,NaN,NaN,12.4,NaN,NaN,V,NaN,NaN,NaN,V,NaN
40510,28,79,106,Centro Mpal. De Acústica,2026-02-28 22:00:00,103.0,55.0,0.0,954.0,1.0,10.8,0.7,V,V,V,V,V,V,V
20254,28,79,103,J.M.D. Villaverde,2026-02-28 22:00:00,109.0,57.0,0.0,953.0,0.0,9.8,1.6,V,V,V,V,V,V,V
10174,28,79,102,J.M.D. Moratalaz,2026-02-28 22:00:00,113.0,62.0,0.0,944.0,0.0,8.3,2.9,V,V,V,V,V,V,V
30358,28,79,104,E.D.A.R. La China,2026-02-28 22:00:00,154.0,NaN,NaN,NaN,NaN,NaN,1.4,V,NaN,NaN,NaN,NaN,NaN,V
60862,28,79,108,Peñagrande,2026-02-28 22:00:00,94.0,57.0,0.0,947.0,0.0,10.2,1.1,V,V,V,V,V,V,V
127990,28,79,115,Matadero 02,2026-02-28 22:00:00,NaN,55.0,NaN,NaN,NaN,13.2,NaN,NaN,V,NaN,NaN,NaN,V,NaN

In [48]:
df_sin_ultima_2_horas = df_sin_ultima_hora[df_sin_ultima_hora["FECHA_HORA"] != ultima_hora]

In [49]:
df_sin_ultima_2_horas.to_csv("historico_expandido_menos_2_horas.csv", index=False, sep=";")

df_sin_ultima_2_horas.to_csv("historico_expandido_DB.csv", index=False, sep=";")

In [50]:
df_sin_ultima_2_horas

MAGNITUD_NOMBRE,PROVINCIA,MUNICIPIO,ESTACION,ESTACION_NOMBRE,FECHA_HORA,Dirección del viento,Humedad relativa,Precipitación,Presión barométrica,Radiación solar,Temperatura,Velocidad del viento,Dirección del viento_valid,Humedad relativa_valid,Precipitación_valid,Presión barométrica_valid,Radiación solar_valid,Temperatura_valid,Velocidad del viento_valid
127989,28,79,115,Matadero 02,2026-02-28 21:00:00,NaN,49.0,NaN,NaN,NaN,14.3,NaN,NaN,V,NaN,NaN,NaN,V,NaN
60861,28,79,108,Peñagrande,2026-02-28 21:00:00,84.0,52.0,0.0,946.0,0.0,10.7,1.6,V,V,V,V,V,V,V
40509,28,79,106,Centro Mpal. De Acústica,2026-02-28 21:00:00,58.0,50.0,0.0,954.0,0.0,11.8,1.6,V,V,V,V,V,V,V
79629,28,79,110,J.M.D. Centro,2026-02-28 21:00:00,NaN,48.0,NaN,NaN,NaN,14.0,NaN,NaN,V,NaN,NaN,NaN,V,NaN
69813,28,79,109,J.M.D. Chamberí,2026-02-28 21:00:00,NaN,46.0,NaN,NaN,NaN,14.6,NaN,NaN,V,NaN,NaN,NaN,V,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118128,28,79,115,Matadero 02,2025-01-01 00:00:00,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,N,NaN,NaN,NaN,N,NaN
20256,28,79,104,E.D.A.R. La China,2025-01-01 00:00:00,46.0,NaN,NaN,NaN,NaN,NaN,0.0,V,NaN,NaN,NaN,NaN,NaN,V
40512,28,79,107,J.M.D. Hortaleza,2025-01-01 00:00:00,32.0,75.0,0.0,948.0,1.0,1.5,0.8,V,V,V,V,V,V,V
50688,28,79,108,Peñagrande,2025-01-01 00:00:00,196.0,77.0,0.0,951.0,1.0,0.1,0.6,V,V,V,V,V,V,V
0,28,79,102,J.M.D. Moratalaz,2025-01-01 00:00:00,55.0,72.0,0.0,949.0,1.0,1.4,0.7,V,V,V,V,V,V,V